version: '3.8'
services:
  # ---------------------------
  # PostgreSQL
  # ---------------------------
  postgres:
    image: postgres:15.14
    container_name: order_postgres
    restart: always
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: secret
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------------------------
  # Zookeeper (required by Kafka)
  # ---------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: order_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ---------------------------
  # Kafka
  # ---------------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: order_kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ---------------------------
  # Redis
  # ---------------------------
  redis:
    image: redis:7.4
    container_name: order_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# ---------------------------
# Volumes
# ---------------------------
volumes:
  postgres_data:
  redis_data:
